### ISSUE TITLE
Do we put shapefiles of Los Angeles County and LA city together?

### ISSUE THREAD

**Issue by lingyielia** [argo-marketplace/LA-LocalGeo-CrossWalk#5]
Hi, @vr00n 

It seems like some geography data are describing Los Angeles County (e.g. [Los Angeles County Fire Department Division Boundaries](http://egis3.lacounty.gov/dataportal/2016/04/28/los-angeles-county-fire-department-division-boundaties/)) and some are describing LA city (e.g. [LA City Council Districts (2012)](http://egis3.lacounty.gov/dataportal/2012/08/07/la-city-council-districts-2012/)). 

Do we only include those for Los Angeles County or keep both?

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by vr00n** [comment]
Great question! 

@patwater @christophertull @dmarulli  any additionaly insight you have here? 

@lingyielia This is **exactly** why we are building this crosswalk file so that it is able to capture all the various boundaries in a single place. 

Let's play this out:

If we intersect LA County Fire boundaries with LA City Council Districts into a single file, the potential would be to query a point in LA County/City that can display information about Fire Division AND council on the **same** query.

[Here is an example for NYC](http://bit.ly/2C1Z8U0) where I am querying the point 40.775745,-73.952686

This also strikes me as a current need when organizing fire evacuations and coordinating between County, State and City agencies.

**Comment by xd515** [comment]
@vr00n 
I did this part of the intersection, and I found the intersection of LA County/City and Fire Division/Battalion was incomplete.
![image](https://user-images.githubusercontent.com/22032935/34449670-e8364584-ecc8-11e7-8389-2db19c145cb6.png)
Should we apply clipping other than intersecting at this point?

**Comment by lingyielia** [comment]
LA County is our target, I will close this issue.
